betagouv/dsfr-view-components

guide/content/introduction/configuration.slim
guide/layouts/example.slim

- ajout de fichiers `.gitkeep` dans `guide/content/stylesheets/fonts` et `icons` 
- reparation de liens internes et externes cassés dans le guide
- commentaire sur l'inclusion du govuk js

reparer le build nanoc du guide

---

.rubocop.yml
Gemfile
config/rubocop-default.yml
config/rubocop-dsfr-overrides.yml
config/rubocop-govuk-components.yml
config/rubocop-layout.yml
config/rubocop-metrics.yml
config/rubocop-naming.yml
config/rubocop-rails.yml
config/rubocop-rspec.yml
config/rubocop-style.yml
dsfr-components.gemspec

cf #102 reparer lint rubocop
la dependance sur `rubocop-govuk` ne me parait pas très judicieuse à préserver : 
- ça dépend d'une version de rubocop un peu ancienne si je comprends bien 1.15
- on va probablement vouloir en diverger
- il n'y a pas vraiment de raison qu'on garde les mêmes règles de lint que govuk
changements de la PR
- retrait de la dépendance `rubocop-govuk` 
- ajout de dependances sur `rubocop` `rubocop-rails` et `rubocop-rspec`
- copie des configs et fichiers de config `rubocop` depuis la gem `rubocop-govuk`
- ajout d'un fichier de config rubocop d'overrides perso pour dsfr-components, pour faire en sorte que le lint passe
on pourra retirer peu a peu les overrides des fichiers de config si on le souhaite

passage de rubocop-govuk a rubocop classique

---

.gitignore
Makefile
dsfr-components.gemspec

en local j'avais `cannot load such file -- rack/server` quand je lancais `make docs-server`. je pense que c'est parce que la gem `yard` n'etait pas installée. 
je l'ai rajoutée en dépendance de la gem + j'ai modifié le makefile pour passer par bundle
j'ai aussi rajouté `.yardoc` au gitignore meme si je ne suis pas sur de moi, je ne sais pas si on est censé le publier ou non

doc: fix yard server locally

---

.rubocop.yml

cf https://rubydoc.info/gems/rubocop/RuboCop/Cop/Style/HashSyntax

config rubocop to prevent shorthand hash syntax for ruby 3.0

---

app/components/dsfr_component/alert_component.rb
app/helpers/dsfr_components_helper.rb
guide/content/components/alert.slim
guide/lib/examples/alert_helpers.rb
guide/lib/helpers.rb
guide/lib/helpers/content_helpers.rb
guide/lib/helpers/link_helpers.rb
spec/components/dsfr_component/alert_component_spec.rb
spec/dummy/app/views/demos/examples/_alert.html.erb

cf #58 
j'hésite un peu pour le `title` est-ce qu'on devrait utiliser un slot ou un kwarg comme j'ai fait la ? Je n'ai pas trop d'avis
Sur mon "style" d'ecriture des tests  : je générise au minimum les exemples pour que chaque exemple soit lisible de manière contenue sans avoir besoin de se référer à trois niveaux d'héritages, de déclarations de variables dans des contextes RSpec différents.
C'est assez différent de l'approche govuk mais pour le coup elle ne me convient pas trop je trouve leurs tests assez illisible.
je n'ai pas encore activé les comportements de tests communs pour accepter les classes : 
```rb
```
mais ca fera plutot l'affaire d'une autre PR a mon avis
j'ai supprimé le mapping des helpers dans `guide/lib/helpers/content_helpers.rb` des components existants de govuk pour …

component: alert

---

.github/workflows/deploy-guide.yml

c'etait une erreur de ma part il ne faut pas deployer le guide quand on fait des PRs 🤦

prevent gh action from deploying guide on PRs

---

guide/content/stylesheets/components/_highlight.scss
guide/layouts/default.slim
guide/layouts/partials/example.slim

The DSFR has a bunch of CSS variables for colours that will adapt to both light and dark themes.
Also update the example layout to match rouge's default output (it's pre.highlight, not pre > code.highlight)

guide: add a DSFR-friendly colourscheme for the code snippets

---

dsfr-view-components.gemspec
guide/lib/helpers.rb

I set pessimistic constraints on all 3 dependencies with only the major version number so that by default updates patches and minor updates will be considered safe in the future.
major version upgrades : 
- `html-attributes-utils` : 0 -> 1
- `pagy`: 5 -> 6
minor version upgrade for `view_component` to 2.80
I had to backport a patch from govuk-components for the view_component upgrade

upgrade view_component, pagy 6, and html-attributes-utils 1

---

guide/content/components/accordion.haml
guide/content/components/alert.haml
guide/content/components/badge.haml
guide/content/components/tile.haml
guide/layouts/partials/header.haml
guide/lib/helpers/content_helpers.rb
lib/generators/dsfr_component/templates/component.haml.erb

I have inlined the call to the `dsfr_component_doc_link` helper in the component haml guide pages. 
The `alert_info`, `badge_info` etc were only called once and with very simple values. I don't think there's a point in generizing them into full blown helpers. 
This also allows to add the link to the doc directly in the scaffold template.
I also removed the `repository_name` for the same single-usage reason. However I left the `site_title` one as it's used > 3 times.

refactor: inline single-use guide helpers

---

app/helpers/dsfr_components_helper.rb
guide/content/introduction/utilisation.haml
guide/lib/helpers/content_helpers.rb

il y avait deux hashes de mapping entre helper names et component class names, un dans le guide et un dans la gem.
je supprime celui du guide pour n'utiliser que celui de la gem

refactor: deduplicate helper to class name mapping

---

lib/generators/dsfr_component/dsfr_component_generator.rb

this always throw a rubocop error for new components

add trailing newline to helpers.rb in component generator

---

app/components/dsfr_component/tile_component.rb

we seem to have overlooked a dead param 🙄

tile: remove mistaken background param

---

app/components/dsfr_component/base.rb
app/components/dsfr_component/tile_component.html.erb
app/components/dsfr_component/tile_component.rb
guide/content/components/tile.haml
guide/lib/examples/tile_helpers.rb
spec/components/dsfr_component/tile_component_spec.rb

Some DSFR components use titles, such as the `Tile` which uses a `h4`. The level of this heading seems arbitrary in the DSFR examples and does not impact its aspect. However it’s a problem for accessibility : heading levels are supposed to be coherent, you should not follow an `h1` with an `h4` for example. cf [this aXe rule](https://dequeuniversity.com/rules/axe/4.6/heading-order?application=axeAPI) and [RGAA 9.1](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#9.1).
In this PR I introduce a `title_tag` param specific to the `TileComponent`. The pattern will probably be reused in other components, so it makes sense to take some time to consider this param name. I thought about `title_level` or `heading_level` but I feel it’s more explicit to pass `:h3` than `3` as an …

add title_tag param to tiles

---

app/components/dsfr_component/button_component.rb
app/helpers/dsfr_components_helper.rb
guide/content/components/button.haml
guide/lib/examples/button_helpers.rb
guide/lib/helpers.rb
spec/components/dsfr_component/button_component_spec.rb

cf #62
- I used the `label` param name for the actual button content as does the DSFR guide because it’s also possible to set a tag attribute `title` on the `<button>` tag. 
- I used a single `:level` param that takes `:primary, :secondary or :tertiary`. we could also use `primary: true`, `secondary: true`... I don’t really have a preference
- I used an `icon` param that takes the class name without the `fr-icon-` prefix, i.e. `checkbox-line` + a second param `icon_position : :left or :right`. This is quite different from what you had done with the `dsfr_link_to` helper but I believe it’s a better direction. I feel it should be easy to add an icon without thinking about its position, so `icon: "checkbox-line"` should work on its own. I don’t have a strong opinion though.
icons are broken …

component: Button

---

app/components/dsfr_component/modal_component.html.erb
app/components/dsfr_component/modal_component.rb
app/helpers/dsfr_components_helper.rb
guide/content/components/modal.haml
guide/lib/examples/modal_helpers.rb
guide/lib/helpers.rb
spec/components/dsfr_component/modal_component_spec.rb

cf #85 
Note: this is based on #150 as the ModalComponent depends on the ButtonComponent one
- I have not handled the case where you want to use an icon in the title, we can do it later I think
- a modal without an explicit html `id` is pretty much useless since you cannot refer to it in any button to open it. In this PR I’ve left it to the user to pass it with the regular `html_attributes: { id: "modal-1" }` kwarg. I don’t require the presence of this attribute, the component won’t fail if you don’t pass it. It will just be harder to use it (you’d need custom JS). We could instead have an explicitly required `id` param in the component, but it’d be redundant with the `html_attributes` one. I don’t have a strong opinion on this.
- for the buttons slots I’ve made it rather simple : it’s …

component: modal

---

README.md
guide/content/introduction/installation.haml

It took me some time to understand that the gem needs to be manually required in `config/application.rb`.
I also cleaned a bit the comments in the README and added a section with services that use this gem (namely Collectif Objets)
I'm very new to gem development, but I think it’s because the name `dsfr-view-components` does not match the structure `dsfr/components` in the `lib` folder . It’s the case for the original govuk gem too, I don’t really know what’s the idea. 
I tried using an explict `gem 'dsfr-view-components', require: true` in the `Gemfile` to no avail, it would tell me something about folders that don’t exist, pointing in the direction of the previous paragraph.

improve setup doc

---

.rubocop.yml
app/components/dsfr_component/header_component.html.erb
app/components/dsfr_component/header_component.rb
app/components/dsfr_component/header_component/direct_link_component.rb
app/components/dsfr_component/header_component/direct_link_dropdown_component.rb
app/components/dsfr_component/header_component/tool_link_component.rb
app/helpers/dsfr_components_helper.rb
guide/content/components/header.haml
guide/layouts/partials/example.haml
guide/lib/examples/header_helpers.rb
guide/lib/helpers.rb
spec/components/dsfr_component/header_component_spec.rb

I created 3 subcomponents : 
- `ToolLinkComponent`
- `DirectLinkComponent`
- `DirectLinkDropdownComponent` (that is composed of many of the previous one)
I also used a polymorphic slot for direct_links with the types option, cf [viewcomponent doc](https://viewcomponent.org/guide/slots.html#polymorphic-slots) 
This allows calling : 
- `c.with_direct_link_simple title: "thing", path: "#here"`
- or `c.with_direct_link_dropdown title: "other thing" do |cc| ...`
and preserve the order when displaying them in the component view with `direct_links.each do |direct_link|`
The suffix `_simple` is quite unfortunate but I could not find a way to not have this suffix for the default case.

component: header

---

app/components/dsfr_component/tabs_component.html.erb
app/components/dsfr_component/tabs_component.rb
app/components/dsfr_component/tabs_component/tab_component.rb
app/helpers/dsfr_components_helper.rb
guide/content/components/header.haml
guide/content/components/tabs.haml
guide/content/components/tile.haml
guide/layouts/partials/related-info.haml
guide/lib/examples/tabs_helpers.rb
guide/lib/helpers.rb
spec/components/dsfr_component/tabs_component_spec.rb

fix #87
Is `TabsComponent` a good name for the main component? The plural feels weird. We could also name it something like `TabSectionComponent` 
I splat out a `DsfrComponent::TabsComponent::TabComponent` that is slightly weird : 
- it’s main `call` function returns the HTML for the tab panel
- it has a `nav_item` function returns the HTML for the nav item (button or link)
I feel like the `nav_item` method is misplaced but I don’t really know how to make it better. 
We could maybe split out the individual `TabComponent` into two sub-sub-components `TabNavItemComponent` and `TabPanelComponent` but calling it would be a bit verbose: 
```haml
= dsfr_tabs do |tabs|
= tabs.with_tab do |tab|
= tab.with_nav_item(title: "Premier onglet", active: true)
= tab.with_panel do 
Contenu du premier …
```

component: Tabs

---

Gemfile.lock
app/components/dsfr_component/header_component.html.erb
app/components/dsfr_component/header_component.rb
app/components/dsfr_component/header_component/operator_image_component.rb
guide/content/components/header.haml
guide/lib/examples/header_helpers.rb

Cette PR ajoute la possibilité d'avoir un logo opérateur horizontal dans l'en tête (header). Ça va nous être utile pour rdv.anct.gouv.fr
Au passage, on rend aussi l'attribut `title` optionnel pour l'en-tête (conformément à la doc du dsfr), ce qui nous sera aussi utile.
L'exemple dans le guide ressemble à ça :

Ajout d'un logo opérateur horizontal dans l'en-tête

---

.github/workflows/tests.yml

bundler v3 n’est pas compatible avec ruby 2, il faut forcer l’installation de la version 2

fix GitHub Actions CI with ruby 2 versions and bundler

---

.github/workflows/deploy-guide.yml
Gemfile.lock
README.md

on indiquait encore d’utiliser ruby 3.1 dans le readme, et on utilisait 3.1 dans le job CI de deploiement des pages.
Cette PR corrige le bug de deploiement des pages cf ce run où j’avais activé sur cette branche pour vérifier https://github.com/betagouv/dsfr-view-components/actions/runs/12545089263/job/34978748007

MàJ ruby 3.1 vers 3.3 dans le readme et l’action GH de deploiement des pages

---

.github/workflows/deploy-guide.yml

On utilisait https://github.com/peaceiris/actions-gh-pages 
On peut maintenant utiliser les actions « officielles » de GH cf https://github.com/actions/upload-pages-artifact?tab=readme-ov-file#usage
ça ne devrait rien changer

MàJ de la CI pour utiliser les actions de déploiement des pages GH officielles

---

guide/content/components/accordion.haml
guide/content/components/alert.haml
guide/content/components/badge.haml
guide/content/components/button.haml
guide/content/components/modal.haml
guide/content/components/tabs.haml
guide/content/components/tag.haml
guide/content/components/tile.haml

Dans le guide, tous les titres de composants ne sont pas uniformes.
Cette PR vise à utiliser la même nomenclature pour toutes les pages, et à suivre les noms de la documentation officielle du DSFR.

Uniformisation des titres dans le guide

---

guide/content/components/accordion.haml
guide/content/components/alert.haml
guide/content/components/badge.haml
guide/content/components/breadcrumbs.haml
guide/content/components/button.haml
guide/content/components/callout.haml
guide/content/components/header.haml
guide/content/components/highlight.haml
guide/content/components/modal.haml
guide/content/components/skiplink.haml
guide/content/components/stepper.haml
guide/content/components/tabs.haml
guide/content/components/tag.haml
guide/content/components/tile.haml
guide/lib/helpers/content_helpers.rb

Depuis la version 1.13 du DSFR, le Storybook est devenu un outil incontournable et la source principale de vérité (en attendant les évolutions de la documentation dans la 1.14, notamment la potentielle introduction du storybook directement dans la documentation).
Je propose donc d’ajouter les liens vers le storybook dans la doc de la gem également.

Ajout des liens vers le storybook

---

dsfr-view-components.gemspec

Nous avons un hash de méta données qui n’est aujourd’hui pas utilisé dans le gemspec. Les différents liens n’apparaissent donc pas sur la page Rubygems.

Add gemspec metadata

---

lib/generators/dsfr_component/templates/component.haml.erb

Lorsque nous avons changé la signature de la méthode `dsfr_component_doc_link` en `dsfr_component_doc_links` dans #214 nous avons oublié de changer le template utilisé par le générateur.

Fix: liens vers la documentation du composant

---

app/components/dsfr_component/alert_component.rb
guide/content/components/alert.haml
guide/lib/examples/alert_helpers.rb
spec/components/dsfr_component/alert_component_spec.rb

En explorant le storybook du DSFR je me suis rendu compte de 2 choses :
- Il est possible d’avoir une alerte « par défaut » de couleur grise
- Cette alerte par défaut permet d’avoir une icône personnalisée
On ajoute donc cette possibilité au composant dans cette PR.

Icône personnalisé pour les alertes par défaut

---

app/components/dsfr_component/notice_component.html.erb
app/components/dsfr_component/notice_component.rb
app/helpers/dsfr_components_helper.rb
guide/content/components/notice.haml
guide/lib/examples/notice_helpers.rb
guide/lib/helpers.rb
spec/components/dsfr_component/notice_component_spec.rb

Ajout du composant d’information importante (Notice)

---

app/components/dsfr_component/notice_component.rb

Une petite typo s’est glissée dans un des types de notice. On l’a corrige !

fix(notice): typo warning type

---

app/components/dsfr_component/accordion_component/section_component.html.erb
spec/components/dsfr_component/accordion_component_spec.rb

When an accordion is inside a form, clicking the button submits the form instead of toggling the section. 
See https://storybook.systeme-de-design.gouv.fr/?path=%2Fdocs%2Faccordion--docs

fix: Add missing button type="button" to accordion section toggler
